import { RegularExpression, Wildcard } from 'objectmaphelper.js';

export var mainWindowMainWindow = {"name": "MainWindow", "type": "MainWindow", "visible": 1};
export var mainWindowGroupBoxMachineControlQGroupBox = {"name": "groupBox_machineControl", "type": "QGroupBox", "visible": 1, "window": mainWindowMainWindow};
export var groupBoxMachineControlPushButtonConnectQPushButton = {"container": mainWindowGroupBoxMachineControlQGroupBox, "name": "pushButton_connect", "type": "QPushButton", "visible": 1};
export var mainWindowGroupBoxSettingsQGroupBox = {"name": "groupBox_settings", "type": "QGroupBox", "visible": 1, "window": mainWindowMainWindow};
export var groupBoxSettingsHorizontalSliderSpeedQSlider = {"container": mainWindowGroupBoxSettingsQGroupBox, "name": "horizontalSlider_speed", "type": "QSlider", "visible": 1};
export var mainWindowGroupBoxInputQGroupBox = {"name": "groupBox_input", "type": "QGroupBox", "visible": 1, "window": mainWindowMainWindow};
export var groupBoxInputTextEditInputQTextEdit = {"container": mainWindowGroupBoxInputQGroupBox, "name": "textEdit_input", "type": "QTextEdit", "visible": 1};
export var groupBoxSettingsPushButtonClearInputQPushButton = {"container": mainWindowGroupBoxSettingsQGroupBox, "name": "pushButton_clearInput", "type": "QPushButton", "visible": 1};
export var mainWindowGroupBoxMachineStatusQGroupBox = {"name": "groupBox_machineStatus", "type": "QGroupBox", "visible": 1, "window": mainWindowMainWindow};
export var groupBoxMachineStatusLabelConnectionStatusQLabel = {"container": mainWindowGroupBoxMachineStatusQGroupBox, "name": "label_connectionStatus", "type": "QLabel", "visible": 1};
export var groupBoxSettingsLabelSpeedValueQLabel = {"container": mainWindowGroupBoxSettingsQGroupBox, "name": "label_speedValue", "type": "QLabel", "visible": 1};
export var groupBoxMachineControlPushButtonStartQPushButton = {"container": mainWindowGroupBoxMachineControlQGroupBox, "name": "pushButton_start", "type": "QPushButton", "visible": 1};
export var groupBoxMachineStatusLabelErrorStatusQLabel = {"container": mainWindowGroupBoxMachineStatusQGroupBox, "name": "label_errorStatus", "type": "QLabel", "visible": 1};
export var groupBoxMachineControlPushButtonResetErrorAndEStopQPushButton = {"container": mainWindowGroupBoxMachineControlQGroupBox, "name": "pushButton_resetErrorAndEStop", "type": "QPushButton", "visible": 1};
export var groupBoxMachineStatusLabelRunningStatusQLabel = {"container": mainWindowGroupBoxMachineStatusQGroupBox, "name": "label_runningStatus", "type": "QLabel", "visible": 1};
export var groupBoxMachineStatusLabelEStopStatusQLabel = {"container": mainWindowGroupBoxMachineStatusQGroupBox, "name": "label_eStopStatus", "type": "QLabel", "visible": 1};
export var qMessageBox = {"type": "QMessageBox", "unnamed": 1, "visible": 1};
export var oKQPushButton = {"text": "OK", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": qMessageBox};
